### ISSUE TITLE
1.20.x Port

### ISSUE THREAD

**Issue by badooga** [spoorn/StepItUp#4]
After fumbling about for 2 hours with no knowledge of how Java works, I managed to make some edits that allow the mod to work on 1.20.x. In `ClientPlayerEntityMixin.java`, I was encountering the error `stepHeight has private access in Entity`, so I replaced the code

```java
if (ModConfig.get().enableStepUp && (!this.isSneaking() || ModConfig.get().enableStepUpWhenSneaking)) {
    if (originalStepHeight < 0) {
        originalStepHeight = thisEntity.stepHeight;
    }
    thisEntity.stepHeight = 1.25f;
} else {
    thisEntity.stepHeight = originalStepHeight;
}
```

with this:

```java
if (ModConfig.get().enableStepUp && (!this.isSneaking() || ModConfig.get().enableStepUpWhenSneaking)) {
    if (originalStepHeight < 0) {
        originalStepHeight = thisEntity.getStepHeight();
    }
    thisEntity.setStepHeight(1.25f);
} else {
    thisEntity.setStepHeight(originalStepHeight);
}
```
This change made the mod work for me on Fabric 1.20.1.

I made this an issue rather than a pull request because I haven't had the chance to test it on Forge, and the environment I did all of this in was really scuffed and required extra modifications to get it to work, so I can't guarantee anything.

**Comment by spoorn** [comment]
Thanks, looks good!
