### ISSUE TITLE
Bug When Disabled

### ISSUE THREAD

**Issue by badooga** [spoorn/StepItUp#6]
When the mod is disabled via the config, you will be unable to walk up slopes like stairs and slabs at all.

Tested on Fabric ~~1.19.4~~ 1.19.2 and 1.20.1

**Comment by spoorn** [comment]
do you have other mods?  It's working on my end

**Comment by badooga** [comment]
To elaborate, it was tested on the Fabulously Optimized 1.19.2 Fabric modpack and the most recent Additive 1.20.1 Quilt modpack. When the first setting to toggle step up is disabled, the player step height is set to zero, preventing them from traversing even the smallest height increases, such as carpets.

I just did some testing, and it seems to be an incompatibility with the Lithium mod - without Lithium, the disabled config option works as intended.

**Comment by spoorn** [comment]
Thanks! will be fixed in next release
